# Generated by Django 5.2.8 on 2025-12-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['user', 'name', 'type'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
