# Generated by Django 5.2.8 on 2025-12-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='transactions.tag'),
        ),
        migrations.DeleteModel(
            name='TransactionTag',
        ),
    ]
